openapi: 3.0.1
info:
  termsOfService: https://notifichedigitali.pagopa.it/pubbliche-amministrazioni/index.html
  title: OpenAPI definition
  version: 3.0.0
  description: api for generating PDF files for F24 forms
  x-summary: sample api for F24
  contact:
    email: pn-supporto-enti@pagopa.it
  license:
    name: Licenza di PN
    url: "https://notifichedigitali.pagopa.it/pubbliche-amministrazioni/index.html"
servers:
  - url: https://localhost:8080
    description: Generated server url
tags:
  - name: f-24-controller
  - name: status
paths:
  /f24/savemeta/{setId}:
    put:
      tags:
        - f-24-controller
      description: Salva tutti i metadati per uno SetId per scopi futuri
      operationId: savemeta
      parameters:
        - $ref: '#/components/parameters/pathSetId'
      requestBody:
        required: true
        content:
         application/json:
             schema:
               $ref: "#/components/schemas/SaveF24Request"
      responses:
        "204":
          description: elaborazione completata positivamente
        "400":
          description: Bad request
          content:
           application/problem+json:
             schema:
               $ref: '#/components/schemas/Problem'
        "500":
         description: Internal error
         content:
           application/problem+json:
             schema:
               $ref: '#/components/schemas/Problem'
  /f24/validate/{setId}:
    get:
      tags:
        - f-24-controller
      description: Valida tutti i metadati per uno SetId. Valutare se validare anche i CF/P.IVA. La validazione è asincrona >-
        per permettere eventuali operazioni complesse.
      operationId: validate
      parameters:
        - $ref: '#/components/parameters/pathSetId'
      responses:
        "204":
          description: request accepted
        "400":
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        "404":
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        "500":
         description: Internal error
         content:
           application/problem+json:
             schema:
               $ref: '#/components/schemas/Problem'
      callbacks:
        f24ValidationUpdates:
          nome_coda_risposta:
            post:
              summary: Eventi validazione spediti ad SQS
              requestBody:
                content:
                  application/json:
                    schema:
                      maxItems: 1000
                      minItems: 1
                      type: array
                      items:
                        $ref: '#/components/schemas/F24ValidationUpdate'
                required: true
              responses:
                default:
                  description: "Error processing the update, the update must be re-sended"
                "200":
                  description: Update correctly received
                "400":
                  description: Malformed update status


  /f24/pdf/{setId}:
    get:
      tags:
        - f-24-controller
      description: Genera (o recupera dalla cache) un documento PDF relativo all'F24 richiesto e ritorna il presigned-url per poterlo scaricare, se disponibile. >-
        Sebbene la generazione e il salvataggio del PDF sia asincrono, il metodo aspetta un tempo configurabile per provare a tornare il presignedUrl con un'unica invocazione. >-
        Se comunque a valle dell'attesa, il documento non è disponibile, popola il valore di retryAfter.
      operationId: generatePDF
      parameters:
        - $ref: '#/components/parameters/pathSetId'
        - $ref: '#/components/parameters/queryCost'
        - $ref: '#/components/parameters/queryPathTokens'
      responses:
        "200":
          description: PDF for Standard form successfully generated.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/F24Response"
        "400":
          description: Bad request
          content:
           application/problem+json:
             schema:
               $ref: '#/components/schemas/Problem'
        "404":
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        "500":
         description: Internal error
         content:
           application/problem+json:
             schema:
               $ref: '#/components/schemas/Problem'
  /f24/prepare/{requestId}:
    post:
     tags:
       - f-24-controller
     description:  Genera (o recupera dalla cache) una serie di documenti PDF F24,
     operationId: preparePDF
     parameters:
       - $ref: '#/components/parameters/pathRequestId'
     requestBody:
       required: true
       content:
         application/json:
             schema:
               $ref: "#/components/schemas/PrepareF24Request"
     responses:
       "204":
         description: Successful
       "400":
         description: Bad request
         content:
          application/problem+json:
            schema:
              $ref: '#/components/schemas/Problem'
       "404":
         description: Not found
         content:
           application/problem+json:
             schema:
               $ref: '#/components/schemas/Problem'
       "500":
        description: Internal error
        content:
          application/problem+json:
            schema:
              $ref: '#/components/schemas/Problem'
     callbacks:
       f24Updates:
         nome_coda_risposta:
           post:
             summary: Eventi avanzamento spediti ad SQS
             requestBody:
               content:
                 application/json:
                   schema:
                     maxItems: 1000
                     minItems: 1
                     type: array
                     items:
                       $ref: '#/components/schemas/F24Update'
               required: true
             responses:
               default:
                 description: "Error processing the update, the update must be re-sended"
               "200":
                 description: Update correctly received
               "400":
                 description: Malformed update status
  /status:
    get:
      tags:
        - status
      operationId: status
      description: Get resulting status.
      responses:
        "200":
          description: Servers finished without errors.
        "400":
          description: Bad request
          content:
           application/problem+json:
             schema:
               $ref: '#/components/schemas/Problem'
        "500":
         description: Internal error
         content:
           application/problem+json:
             schema:
               $ref: '#/components/schemas/Problem'


components:
  schemas:
    F24Response:
      type: object
      properties:
        url:
          type: string
          description: >-
            URL per il download del contenuto del documento.
            example: 'https://preloadpn.aws.amazon.......'
        retryAfter:
          type: number
          description: >-
            Stima del numero di secondi da aspettare prima che il contenuto del
            documento sia scaricabile.
    SaveF24Request:
      type: object
      required:
        - setId
      properties:
        setId:
          type: string
          description: Identificativo SetId della richiesta. E' lo stesso usato nel path
            del metodo
          example: ABCD-HILM-YKWX-202202-1
        f24Items:
          $ref: './schemas-f24.yaml#/components/schemas/F24ItemArray'
    PrepareF24Request:
      type: object
      required:
        - setId
        - requestId
      properties:
        requestId:
          type: string
          description: Identificativo della richiesta. E' lo stesso usato nel path
            del metodo
          example: ABCD-HILM-YKWX-202202-1_rec0_try1
        setId:
          type: string
          minLength: 1
        pathTokens:
          type: array
          items:
            type: string
          description: Identificativo id path
        notificationCost:
          type: integer
          format: int32
          nullable: true
          description: notification cost in eurocent to include, obbligatorio se i documenti prevedono l'aggiornamento con il costo della notifica.
    F24Update:
      type: object
      properties:
        requestId:
          type: string
          description: Identificativo della richiesta. E' usato per correlare la risposta alla richiesta
          example: ABCD-HILM-YKWX-202202-1_rec0_try1
        paymentUrls:
          type: array
          description: Array di URL di safestorage. preserva l'ordine con cui sono letti i metadati
          items:
           type: string
           description: URL di safe storage
      description: oggetto usato per ricevere un evento nella coda.
    F24ValidationUpdate:
      type: object
      properties:
        setId:
          type: string
          description: SetId usato nella richiesta
        results:
          type: array
          items:
            $ref: '#/components/schemas/F24ValidationUpdateResultItem'
      description: oggetto usato per ricevere un evento nella coda.
    F24ValidationUpdateResultItem:
      type: object
      properties:
        result:
          type: string
          description: risultato della validazione
          enum:
            - OK
            - KO
        detail:
          type: string
          description: dettaglio dell'eventuale KO di validazione
        pathTokens:
          type: array
          items:
            type: string
          description: Identificativo id path
    Problem:
      $ref: './remote-refs.yaml#/components/schemas/Problem'

  parameters:

    ############################################################################################
    ###                             PARAMETRI GENERAZIONE F24                                ###
    ############################################################################################
    pathSetId:
      description: >-
        Identificativo Univoco Set di Metadati
      name: setId
      in: path
      required: true
      schema:
        type: string
        minLength: 1

    queryPathTokens:
      in: query
      name: pathTokens
      description: Identificativo id query
      schema:
        type: array
        items:
          type: string


    queryCost:
      description: >-
        Costo della notifica in eurocent
      name: cost
      in: query
      required: false
      schema:
        type: integer

    pathRequestId:
      description: >-
        Identificativo requestId
      name: requestId
      in: path
      required: true
      schema:
        type: string